### PR TITLE
Improve upstream remote determination

### PR DESCRIPTION
**Pull request by dnd**
Here's my initial work from what I brought up in issue #2. 

When deploying via copy the remote will be chosen if only one is present. The remote can also be specified using the :upstream_remote_name variable in the event that multiple remotes are available.

### CODE REVIEW

**Comment by jrochkind** [comment]
Makes sense, nicely done, will merge, and then release new version of cap_git_tools I guess?

Should we update the docs to mention this, or is it enough that someone can look at the source?

Would you like commit rights to cap_git_tools?

**Comment by dnd** [comment]
Yeah, i can add some documentation. I just didn't want to write anything in
the event that it might be changed substantially, or just rejected.

I dont have any immediate other ideas for the library(except for maybe
using the rugged gem?), but if you want to give me commit rights I'm okay
with that.

**Comment by jrochkind** [comment]
Yep, I'll give you commit, in case you run into something else that needs to be fixed, or feel like doing something, heh. 

I am not familiar with rugged. I just looked it up... interesting. Do you think that would make sense, maybe make things more robust/reliable?  

Will add you as a committer soon as I figure out how. No problem if you end up doing nothing with it. Thanks for the contribution!

**Comment by dnd** [comment]
Rugged does look like it might make things cleaner. Instead of sending out command line commands, the code would interact with an actual API. I don't know what further plans if any you had for the project. If there isn't much more expansion planned right now, I don't see the need to bother with it. 

The one downside, is that it looks like rugged would be somewhat complicated to use for Windows users. It would require them to have Visual Studio so that they can compile libgit2. I'm not sure if that requires a paid version of VS, or if there's a free one that could be used.

**Comment by dnd** [comment]
Checking the libgit2 wiki page on building for windows, it's possible to use MinGW. Whether it's VS or MinGW, there's still quite a bit to do to install on Windows.

https://github.com/libgit2/libgit2/wiki/Building-libgit2-on-Windows

**Comment by jrochkind** [comment]
Interesting. I have no idea if the current solution, with a shell-out to
command line git... actually works for windows users or not. Do you have
any idea?

Also, can you tell if a libgit2/rugged solution would be runnable under
jruby? (I dont' know how important it is for one's cap to be runnable under
jruby, but just wondering)

**Pull request merged**
